/**
 * routes/activityLog.js
 * Migrated to MongoDB for cloud persistence.
 */
import { Router } from 'express';
import { ActivityLog } from '../models/UserModels.js';

const router = Router();

// GET /activityLog — retrieve today's events (newest first)
router.get('/', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit, 10) || 500;
    const today = new Date().toISOString().split('T')[0];
    const entries = await ActivityLog.find({ date: today })
      .sort({ ts: -1 })
      .limit(limit)
      .lean();
    res.json(entries);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// GET /activityLog/files — list all available log dates
router.get('/files', async (req, res) => {
  try {
    const dates = await ActivityLog.distinct('date');
    // Sort newest date first
    res.json(dates.sort((a, b) => b.localeCompare(a)));
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// GET /activityLog/:date — get log for a specific date
router.get('/:date', async (req, res) => {
  try {
    const entries = await ActivityLog.find({ date: req.params.date })
      .sort({ ts: -1 })
      .lean();
    if (entries.length === 0) return res.status(404).json({ error: 'Log not found' });
    res.json(entries);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// POST /activityLog
router.post('/', async (req, res) => {
  try {
    // ts and date are automatically generated by Mongoose schema defaults
    const entry = await ActivityLog.create(req.body);
    res.status(201).json(entry);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// DELETE /activityLog — clear today's log
router.delete('/', async (req, res) => {
  try {
    const today = new Date().toISOString().split('T')[0];
    await ActivityLog.deleteMany({ date: today });
    res.json({ cleared: true });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
