#!/usr/bin/env python3
"""
reclassify_a1.py

Reclassifies A1 vocabulary into well-sized categories (5–30 words each).
Uses a static word→category mapping keyed by (word, class) to avoid ambiguity.
Preserves all 1076 words. Only modifies the 'a1' key in oxford_classified.json.
"""

import json, os, re, sys
from collections import defaultdict
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from flat_utils import load_flat, flat_to_nested, replace_level, save_flat

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
CLASSIFIED    = os.path.join(SCRIPT_DIR, '..', 'oxford_classified.json')

# ────────────────────────────────────────────────────────────────────────────
# STATIC REMAPPING  { (word, class): "New Category" }
# Words not listed here keep their current category (if it's already OK)
# or fall into the catch-all handler below.
# ────────────────────────────────────────────────────────────────────────────
REMAP = {

    # ── Personal Pronouns (subject + object + possessive) ─────────────────
    ("I",          "pronoun"):       "Personal Pronouns",
    ("me",         "pronoun"):       "Personal Pronouns",
    ("him",        "pronoun"):       "Personal Pronouns",
    ("her",        "pronoun"):       "Personal Pronouns",
    ("her",        "determiner"):    "Personal Pronouns",
    ("us",         "pronoun"):       "Personal Pronouns",
    ("you",        "pronoun"):       "Personal Pronouns",
    ("he",         "pronoun"):       "Personal Pronouns",
    ("she",        "pronoun"):       "Personal Pronouns",
    ("they",       "pronoun"):       "Personal Pronouns",
    ("we",         "pronoun"):       "Personal Pronouns",
    ("it",         "pronoun"):       "Personal Pronouns",
    ("my",         "determiner"):    "Personal Pronouns",
    ("your",       "determiner"):    "Personal Pronouns",
    ("his",        "determiner"):    "Personal Pronouns",
    ("our",        "determiner"):    "Personal Pronouns",
    ("their",      "determiner"):    "Personal Pronouns",
    ("its",        "determiner"):    "Personal Pronouns",
    ("this",       "determiner"):    "Personal Pronouns",
    ("this",       "pronoun"):       "Personal Pronouns",
    ("that",       "determiner"):    "Personal Pronouns",
    ("these",      "determiner"):    "Personal Pronouns",
    ("those",      "determiner"):    "Personal Pronouns",
    ("them",       "pronoun"):       "Personal Pronouns",

    # ── Quantifiers & Indefinite Pronouns ─────────────────────────────────
    ("each",       "determiner"):    "Quantifiers & Determiners",
    ("each",       "pronoun"):       "Quantifiers & Determiners",
    ("each",       "adverb"):        "Quantifiers & Determiners",
    ("every",      "determiner"):    "Quantifiers & Determiners",
    ("all",        "determiner"):    "Quantifiers & Determiners",
    ("all",        "pronoun"):       "Quantifiers & Determiners",
    ("all",        "adverb"):        "Quantifiers & Determiners",
    ("some",       "determiner"):    "Quantifiers & Determiners",
    ("some",       "pronoun"):       "Quantifiers & Determiners",
    ("many",       "determiner"):    "Quantifiers & Determiners",
    ("many",       "pronoun"):       "Quantifiers & Determiners",
    ("more",       "determiner"):    "Quantifiers & Determiners",
    ("more",       "pronoun"):       "Quantifiers & Determiners",
    ("more",       "adverb"):        "Quantifiers & Determiners",
    ("most",       "determiner"):    "Quantifiers & Determiners",
    ("most",       "pronoun"):       "Quantifiers & Determiners",
    ("most",       "adverb"):        "Quantifiers & Determiners",
    ("much",       "determiner"):    "Quantifiers & Determiners",
    ("much",       "pronoun"):       "Quantifiers & Determiners",
    ("much",       "adverb"):        "Quantifiers & Determiners",
    ("much",       "adjective"):     "Quantifiers & Determiners",
    ("few",        "determiner"):    "Quantifiers & Determiners",
    ("few",        "pronoun"):       "Quantifiers & Determiners",
    ("few",        "adjective"):     "Descriptive Adjectives",
    ("any",        "determiner"):    "Quantifiers & Determiners",
    ("any",        "pronoun"):       "Quantifiers & Determiners",
    ("any",        "adverb"):        "Quantifiers & Determiners",
    ("another",    "determiner"):    "Quantifiers & Determiners",
    ("another",    "pronoun"):       "Quantifiers & Determiners",
    ("both",       "determiner"):    "Quantifiers & Determiners",
    ("both",       "pronoun"):       "Quantifiers & Determiners",
    ("other",      "adjective"):     "Personal Pronouns",
    ("other",      "pronoun"):       "Personal Pronouns",
    ("one",        "pronoun"):       "Quantifiers & Determiners",
    ("one",        "determiner"):    "Quantifiers & Determiners",
    ("same",       "adjective"):     "Core Adjectives",
    ("same",       "adverb"):        "Core Adjectives",
    ("same",       "pronoun"):       "Core Adjectives",
    ("no",         "determiner"):    "Indefinite Expressions",
    ("no",         "exclamation"):   "Greetings & Expressions",
    ("nothing",    "pronoun"):       "Quantifiers & Determiners",
    ("nobody",     "pronoun"):       "Quantifiers & Determiners",
    ("everybody",  "pronoun"):       "Quantifiers & Determiners",
    ("everyone",   "pronoun"):       "Quantifiers & Determiners",
    ("someone",    "pronoun"):       "Quantifiers & Determiners",
    ("somebody",   "pronoun"):       "Quantifiers & Determiners",
    ("something",  "pronoun"):       "Quantifiers & Determiners",
    ("everything", "pronoun"):       "Quantifiers & Determiners",
    ("no one",     "pronoun"):       "Quantifiers & Determiners",
    ("anything",   "pronoun"):       "Quantifiers & Determiners",
    ("lot",        "noun"):          "Quantifiers & Determiners",
    ("lot",        "pronoun"):       "Quantifiers & Determiners",
    ("lot",        "adverb"):        "Quantifiers & Determiners",
    ("lot",        "determiner"):    "Quantifiers & Determiners",

    # ── Indefinite Expressions ───────────────────────────────────────────────
    ("nobody",     "pronoun"):       "Indefinite Expressions",
    ("everybody",  "pronoun"):       "Indefinite Expressions",
    ("everyone",   "pronoun"):       "Indefinite Expressions",
    ("someone",    "pronoun"):       "Indefinite Expressions",
    ("somebody",   "pronoun"):       "Indefinite Expressions",
    ("something",  "pronoun"):       "Indefinite Expressions",
    ("everything", "pronoun"):       "Indefinite Expressions",
    ("no one",     "pronoun"):       "Indefinite Expressions",
    ("anything",   "pronoun"):       "Indefinite Expressions",
    ("nothing",    "pronoun"):       "Indefinite Expressions",
    ("each",       "determiner"):    "Indefinite Expressions",
    ("each",       "pronoun"):       "Indefinite Expressions",
    ("each",       "adverb"):        "Indefinite Expressions",
    ("every",      "determiner"):    "Indefinite Expressions",

    # ── Modals & Auxiliaries ────────────────────────────────────────────────
    ("can",        "modal verb"):    "Modals & Auxiliaries",
    ("cannot",     "modal verb"):    "Modals & Auxiliaries",
    ("could",      "modal verb"):    "Modals & Auxiliaries",
    ("must",       "modal verb"):    "Modals & Auxiliaries",
    ("should",     "modal verb"):    "Modals & Auxiliaries",
    ("would",      "modal verb"):    "Modals & Auxiliaries",
    ("will",       "modal verb"):    "Modals & Auxiliaries",
    ("have to",    "modal verb"):    "Modals & Auxiliaries",
    ("do",         "auxiliary verb"):"Modals & Auxiliaries",
    ("be",         "auxiliary verb"):"Modals & Auxiliaries",
    ("do",         "verb"):          "Modals & Auxiliaries",
    ("be",         "verb"):          "Modals & Auxiliaries",
    ("have",       "verb"):          "Modals & Auxiliaries",
    ("have",       "auxiliary verb"):"Modals & Auxiliaries",

    # ── Grammar Connectors ──────────────────────────────────────────────────
    ("and",        "conjunction"):   "Grammar Connectors",
    ("but",        "conjunction"):   "Grammar Connectors",
    ("or",         "conjunction"):   "Grammar Connectors",
    ("so",         "conjunction"):   "Grammar Connectors",
    ("if",         "conjunction"):   "Grammar Connectors",
    ("than",       "conjunction"):   "Grammar Connectors",
    ("than",       "preposition"):   "Grammar Connectors",
    ("that",       "conjunction"):   "Grammar Connectors",
    ("that",       "pronoun"):       "Grammar Connectors",
    ("when",       "conjunction"):   "Grammar Connectors",
    ("when",       "adverb"):        "Grammar Connectors",
    ("when",       "pronoun"):       "Grammar Connectors",
    ("where",      "conjunction"):   "Grammar Connectors",
    ("where",      "adverb"):        "Grammar Connectors",
    ("which",      "determiner"):    "Grammar Connectors",
    ("which",      "pronoun"):       "Grammar Connectors",
    ("who",        "pronoun"):       "Grammar Connectors",
    ("what",       "determiner"):    "Grammar Connectors",
    ("what",       "pronoun"):       "Grammar Connectors",
    ("why",        "adverb"):        "Grammar Connectors",
    ("how",        "adverb"):        "Grammar Connectors",
    ("however",    "adverb"):        "Grammar Connectors",
    ("about",      "preposition"):   "Grammar Connectors",
    ("about",      "adverb"):        "Grammar Connectors",
    ("as",         "conjunction"):   "Grammar Connectors",
    ("as",         "preposition"):   "Grammar Connectors",
    ("as",         "adverb"):        "Grammar Connectors",
    ("for",        "preposition"):   "Grammar Connectors",

    # ── Grammar Adverbs ─────────────────────────────────────────────────────
    ("not",        "adverb"):        "Grammar Adverbs",
    ("only",       "adverb"):        "Grammar Adverbs",
    ("also",       "adverb"):        "Grammar Adverbs",
    ("often",      "adverb"):        "Grammar Adverbs",
    ("usually",    "adverb"):        "Grammar Adverbs",
    ("sometimes",  "adverb"):        "Grammar Adverbs",
    ("maybe",      "adverb"):        "Grammar Adverbs",
    ("probably",   "adverb"):        "Grammar Adverbs",
    ("quite",      "adverb"):        "Grammar Adverbs",
    ("really",     "adverb"):        "Grammar Adverbs",
    ("just",       "adverb"):        "Grammar Adverbs",
    ("else",       "adverb"):        "Grammar Adverbs",
    ("too",        "adverb"):        "Grammar Adverbs",
    ("so",         "adverb"):        "Grammar Adverbs",
    ("very",       "adverb"):        "Grammar Adverbs",
    ("already",    "adverb"):        "Grammar Adverbs",
    ("always",     "adverb"):        "Grammar Adverbs",
    ("together",   "adverb"):        "Grammar Adverbs",
    ("quickly",    "adverb"):        "Grammar Adverbs",
    ("still",      "adverb"):        "Grammar Adverbs",

    # ── Core Prepositions (function words) ────────────────────────────────
    ("in",         "preposition"):   "Core Prepositions",
    ("in",         "adverb"):        "Core Prepositions",
    ("on",         "preposition"):   "Core Prepositions",
    ("on",         "adverb"):        "Core Prepositions",
    ("at",         "preposition"):   "Core Prepositions",
    ("to",         "preposition"):   "Core Prepositions",
    ("to",         "infinitive marker"): "Core Prepositions",
    ("from",       "preposition"):   "Core Prepositions",
    ("with",       "preposition"):   "Core Prepositions",
    ("by",         "preposition"):   "Core Prepositions",
    ("by",         "adverb"):        "Core Prepositions",
    ("into",       "preposition"):   "Core Prepositions",
    ("through",    "preposition"):   "Core Prepositions",
    ("through",    "adverb"):        "Core Prepositions",
    ("between",    "preposition"):   "Core Prepositions",
    ("without",    "preposition"):   "Core Prepositions",
    ("of",         "preposition"):   "Core Prepositions",
    ("like",       "preposition"):   "Core Prepositions",

    # ── Direction & Position Words ─────────────────────────────────────────
    ("up",         "preposition"):   "Direction & Position Words",
    ("up",         "adverb"):        "Direction & Position Words",
    ("down",       "preposition"):   "Direction & Position Words",
    ("down",       "adverb"):        "Direction & Position Words",
    ("out",        "preposition"):   "Direction & Position Words",
    ("out",        "adverb"):        "Direction & Position Words",
    ("off",        "preposition"):   "Direction & Position Words",
    ("off",        "adverb"):        "Direction & Position Words",
    ("under",      "preposition"):   "Direction & Position Words",
    ("under",      "adverb"):        "Direction & Position Words",
    ("over",       "preposition"):   "Direction & Position Words",
    ("over",       "adverb"):        "Direction & Position Words",
    ("around",     "preposition"):   "Direction & Position Words",
    ("around",     "adverb"):        "Direction & Position Words",
    ("next to",    "preposition"):   "Direction & Position Words",
    ("back",       "adverb"):        "Direction & Position Words",
    ("past",       "preposition"):   "Direction & Position Words",
    ("past",       "adverb"):        "Direction & Position Words",
    ("past",       "noun"):          "Time Expressions",
    ("past",       "adjective"):     "Time Expressions",
    ("left",       "adverb"):        "Direction & Position Words",
    ("left",       "noun"):          "Direction & Position Words",
    ("left",       "adjective"):     "Direction & Position Words",
    ("right",      "adverb"):        "Direction & Position Words",
    ("right",      "noun"):          "Direction & Position Words",
    ("below",      "adverb"):        "Spatial Concepts",
    ("below",      "preposition"):   "Spatial Concepts",
    ("front",      "noun"):          "Spatial Concepts",
    ("front",      "adjective"):     "Spatial Concepts",
    ("outside",    "adverb"):        "Spatial Concepts",
    ("outside",    "preposition"):   "Spatial Concepts",
    ("outside",    "adjective"):     "Spatial Concepts",
    ("outside",    "noun"):          "Spatial Concepts",
    ("opposite",   "adjective"):     "Spatial Concepts",
    ("opposite",   "adverb"):        "Spatial Concepts",
    ("opposite",   "noun"):          "Spatial Concepts",
    ("opposite",   "preposition"):   "Spatial Concepts",
    ("away",       "adverb"):        "Direction & Position Words",
    ("there",      "adverb"):        "Direction & Position Words",
    # Move 3 commonly geographic words out to reduce size
    ("back",       "noun"):          "Direction & Position Words",
    ("guess",      "noun"):          "Daily Routines",
    ("guess",      "verb"):          "Daily Routines",
    ("opinion",    "noun"):          "Communication Basics",

    # ── Core Adjectives (truth / state / quality) ─────────────────────────
    ("good",       "adjective"):     "Core Adjectives",
    ("bad",        "adjective"):     "Core Adjectives",
    ("true",       "adjective"):     "Core Adjectives",
    ("false",      "adjective"):     "Core Adjectives",
    ("correct",    "adjective"):     "Core Adjectives",
    ("correct",    "verb"):          "Core Adjectives",
    ("wrong",      "adjective"):     "Core Adjectives",
    ("real",       "adjective"):     "Core Adjectives",
    ("open",       "adjective"):     "Core Adjectives",
    ("open",       "verb"):          "Core Adjectives",
    ("possible",   "adjective"):     "Core Adjectives",
    ("perfect",    "adjective"):     "Core Adjectives",
    ("complete",   "adjective"):     "Core Adjectives",
    ("complete",   "verb"):          "Core Adjectives",
    ("ready",      "adjective"):     "Core Adjectives",
    ("sure",       "adjective"):     "Core Adjectives",
    ("sure",       "adverb"):        "Core Adjectives",
    ("right",      "adjective"):     "Core Adjectives",
    ("well",       "adverb"):        "Core Adjectives",
    ("well",       "exclamation"):   "Core Adjectives",
    ("only",       "adjective"):     "Core Adjectives",

    # ── Descriptive Adjectives (size / character / evaluation) ────────────
    ("different",  "adjective"):     "Descriptive Adjectives",
    ("interesting","adjective"):     "Descriptive Adjectives",
    ("special",    "adjective"):     "Descriptive Adjectives",
    ("personal",   "adjective"):     "Descriptive Adjectives",
    ("final",      "adjective"):     "Descriptive Adjectives",
    ("main",       "adjective"):     "Descriptive Adjectives",
    ("common",     "adjective"):     "Descriptive Adjectives",
    ("small",      "adjective"):     "Descriptive Adjectives",
    ("big",        "adjective"):     "Descriptive Adjectives",
    ("short",      "adjective"):     "Descriptive Adjectives",
    ("long",       "adjective"):     "Descriptive Adjectives",
    ("new",        "adjective"):     "Descriptive Adjectives",
    ("old",        "adjective"):     "Descriptive Adjectives",
    ("best",       "adjective"):     "Descriptive Adjectives",
    ("best",       "adverb"):        "Descriptive Adjectives",
    ("best",       "noun"):          "Descriptive Adjectives",
    ("favourite",  "adjective"):     "Descriptive Adjectives",
    ("favourite",  "noun"):          "Descriptive Adjectives",
    ("free",       "adjective"):     "Descriptive Adjectives",
    ("full",       "adjective"):     "Descriptive Adjectives",
    ("hard",       "adjective"):     "Descriptive Adjectives",
    ("hard",       "adverb"):        "Descriptive Adjectives",
    ("fast",       "adjective"):     "Descriptive Adjectives",
    ("fast",       "adverb"):        "Descriptive Adjectives",
    ("large",      "adjective"):     "Descriptive Adjectives",
    ("extra",      "adjective"):     "Descriptive Adjectives",
    ("extra",      "adverb"):        "Descriptive Adjectives",
    ("extra",      "noun"):          "Descriptive Adjectives",
    ("fat",        "adjective"):     "Evaluative Adjectives",
    ("difficult",  "adjective"):     "Descriptive Adjectives",
    ("easy",       "adjective"):     "Descriptive Adjectives",
    ("amazing",    "adjective"):     "Evaluative Adjectives",
    ("fantastic",  "adjective"):     "Evaluative Adjectives",
    ("nice",       "adjective"):     "Evaluative Adjectives",
    ("quiet",      "adjective"):     "Evaluative Adjectives",
    ("rich",       "adjective"):     "Evaluative Adjectives",
    ("terrible",   "adjective"):     "Evaluative Adjectives",
    ("young",      "adjective"):     "Evaluative Adjectives",
    ("late",       "adverb"):        "Evaluative Adjectives",
    ("late",       "adjective"):     "Evaluative Adjectives",
    ("key",        "adjective"):     "Evaluative Adjectives",
    ("busy",       "adjective"):     "Evaluative Adjectives",
    ("friendly",   "adjective"):     "Evaluative Adjectives",
    ("married",    "adjective"):     "Evaluative Adjectives",

    # ── Numbers 1–20 ────────────────────────────────────────────────────────
    ("one",        "number"):        "Numbers 1-20",
    ("two",        "number"):        "Numbers 1-20",
    ("three",      "number"):        "Numbers 1-20",
    ("four",       "number"):        "Numbers 1-20",
    ("five",       "number"):        "Numbers 1-20",
    ("six",        "number"):        "Numbers 1-20",
    ("seven",      "number"):        "Numbers 1-20",
    ("eight",      "number"):        "Numbers 1-20",
    ("nine",       "number"):        "Numbers 1-20",
    ("ten",        "number"):        "Numbers 1-20",
    ("eleven",     "number"):        "Numbers 1-20",
    ("twelve",     "number"):        "Numbers 1-20",
    ("thirteen",   "number"):        "Numbers 1-20",
    ("fourteen",   "number"):        "Numbers 1-20",
    ("fifteen",    "number"):        "Numbers 1-20",
    ("sixteen",    "number"):        "Numbers 1-20",
    ("seventeen",  "number"):        "Numbers 1-20",
    ("eighteen",   "number"):        "Numbers 1-20",
    ("nineteen",   "number"):        "Numbers 1-20",
    ("twenty",     "number"):        "Numbers 1-20",
    ("first",      "ordinal number"):"Numbers 1-20",
    ("second",     "ordinal number"):"Numbers 1-20",
    ("third",      "ordinal number"):"Numbers 1-20",
    ("fourth",     "ordinal number"):"Numbers 1-20",
    ("fifth",      "ordinal number"):"Numbers 1-20",

    # ── Large Numbers & Units ─────────────────────────────────────────────
    ("thirty",     "number"):        "Large Numbers & Units",
    ("forty",      "number"):        "Large Numbers & Units",
    ("fifty",      "number"):        "Large Numbers & Units",
    ("sixty",      "number"):        "Large Numbers & Units",
    ("seventy",    "number"):        "Large Numbers & Units",
    ("eighty",     "number"):        "Large Numbers & Units",
    ("ninety",     "number"):        "Large Numbers & Units",
    ("hundred",    "number"):        "Large Numbers & Units",
    ("thousand",   "number"):        "Large Numbers & Units",
    ("million",    "number"):        "Large Numbers & Units",
    ("kilometre",  "noun"):          "Large Numbers & Units",
    ("metre",      "noun"):          "Large Numbers & Units",
    ("mile",       "noun"):          "Large Numbers & Units",
    ("number",     "noun"):          "Large Numbers & Units",
    ("half",       "noun"):          "Large Numbers & Units",
    ("half",       "pronoun"):       "Large Numbers & Units",
    ("half",       "determiner"):    "Large Numbers & Units",
    ("half",       "adverb"):        "Large Numbers & Units",
    ("piece",      "noun"):          "Large Numbers & Units",
    ("enough",     "determiner"):    "Large Numbers & Units",
    ("enough",     "pronoun"):       "Large Numbers & Units",
    ("enough",     "adverb"):        "Large Numbers & Units",

    # ── Time Expressions ────────────────────────────────────────────────────
    ("morning",    "noun"):          "Clock & Time",
    ("afternoon",  "noun"):          "Clock & Time",
    ("evening",    "noun"):          "Clock & Time",
    ("night",      "noun"):          "Clock & Time",
    ("midnight",   "noun"):          "Clock & Time",
    ("o'clock",    "adverb"):        "Clock & Time",
    ("clock",      "noun"):          "Clock & Time",
    ("quarter",    "noun"):          "Clock & Time",
    ("tonight",    "adverb"):        "Clock & Time",
    ("tonight",    "noun"):          "Clock & Time",
    ("today",      "adverb"):        "Clock & Time",
    ("today",      "noun"):          "Clock & Time",
    ("yesterday",  "adverb"):        "Clock & Time",
    ("yesterday",  "noun"):          "Clock & Time",
    ("tomorrow",   "adverb"):        "Clock & Time",
    ("tomorrow",   "noun"):          "Clock & Time",
    ("now",        "adverb"):        "Clock & Time",
    ("week",       "noun"):          "Clock & Time",
    ("weekend",    "noun"):          "Clock & Time",
    ("time",       "noun"):          "Clock & Time",
    ("after",      "preposition"):   "Time Expressions",
    ("after",      "conjunction"):   "Time Expressions",
    ("after",      "adverb"):        "Time Expressions",
    ("until",      "conjunction"):   "Time Expressions",
    ("until",      "preposition"):   "Time Expressions",
    ("future",     "noun"):          "Time Expressions",
    ("future",     "adjective"):     "Time Expressions",
    ("end",        "noun"):          "Time Expressions",
    ("end",        "verb"):          "Time Expressions",
    ("beginning",  "noun"):          "Time Expressions",
    ("next",       "adjective"):     "Time Expressions",
    ("next",       "adverb"):        "Time Expressions",
    ("next",       "noun"):          "Time Expressions",
    ("first",      "adverb"):        "Time Expressions",
    ("first",      "determiner"):    "Time Expressions",
    ("first",      "noun"):          "Time Expressions",
    ("second",     "noun"):          "Time Expressions",
    ("third",      "noun"):          "Time Expressions",
    ("once",       "adverb"):        "Time Expressions",
    ("twice",      "adverb"):        "Time Expressions",
    ("born",       "verb"):          "Time Expressions",

    # ── Greetings & Expressions ─────────────────────────────────────────────
    ("hello",      "exclamation"):   "Greetings & Expressions",
    ("hello",      "noun"):          "Greetings & Expressions",
    ("hi",         "exclamation"):   "Greetings & Expressions",
    ("bye",        "exclamation"):   "Greetings & Expressions",
    ("goodbye",    "exclamation"):   "Greetings & Expressions",
    ("goodbye",    "noun"):          "Greetings & Expressions",
    ("OK",         "adjective"):     "Greetings & Expressions",
    ("OK",         "adverb"):        "Greetings & Expressions",
    ("OK",         "exclamation"):   "Greetings & Expressions",
    ("yeah",       "exclamation"):   "Greetings & Expressions",
    ("yes",        "exclamation"):   "Greetings & Expressions",
    ("thank",      "verb"):          "Greetings & Expressions",
    ("thanks",     "exclamation"):   "Greetings & Expressions",
    ("thanks",     "noun"):          "Greetings & Expressions",
    ("hey",        "exclamation"):   "Greetings & Expressions",
    ("welcome",    "exclamation"):   "Greetings & Expressions",
    ("welcome",    "adjective"):     "Greetings & Expressions",
    ("welcome",    "verb"):          "Greetings & Expressions",
    ("welcome",    "noun"):          "Greetings & Expressions",
    ("please",     "exclamation"):   "Greetings & Expressions",
    ("please",     "verb"):          "Greetings & Expressions",
    ("oh",         "exclamation"):   "Greetings & Expressions",
    ("dear",       "exclamation"):   "Greetings & Expressions",
    ("dear",       "adjective"):     "Greetings & Expressions",

    # ── Communication Basics ────────────────────────────────────────────────
    ("say",        "verb"):          "Communication Basics",
    ("speak",      "verb"):          "Communication Basics",
    ("ask",        "verb"):          "Communication Basics",
    ("answer",     "verb"):          "Communication Basics",
    ("answer",     "noun"):          "Communication Basics",
    ("call",       "verb"):          "Communication Basics",
    ("call",       "noun"):          "Communication Basics",
    ("tell",       "verb"):          "Communication Basics",
    ("listen",     "verb"):          "Communication Basics",
    ("send",       "verb"):          "Communication Basics",
    ("share",      "verb"):          "Communication Basics",
    ("repeat",     "verb"):          "Communication Basics",
    ("repeat",     "noun"):          "Communication Basics",
    ("understand", "verb"):          "Communication Basics",
    ("meet",       "verb"):          "Communication Basics",
    ("agree",      "verb"):          "Communication Basics",
    ("sound",      "verb"):          "Communication Basics",
    ("sound",      "noun"):          "Communication Basics",
    ("again",      "adverb"):        "Communication Basics",

    # ── Language & Study Tools ──────────────────────────────────────────────
    ("word",       "noun"):          "Language & Study Tools",
    ("topic",      "noun"):          "Language & Study Tools",
    ("reason",     "noun"):          "Language & Study Tools",
    ("information","noun"):          "Language & Study Tools",
    ("letter",     "noun"):          "Language & Study Tools",
    ("list",       "noun"):          "Language & Study Tools",
    ("list",       "verb"):          "Language & Study Tools",
    ("point",      "noun"):          "Language & Study Tools",
    ("meaning",    "noun"):          "Language & Study Tools",
    ("mean",       "verb"):          "Language & Study Tools",
    ("phone",      "noun"):          "Language & Study Tools",
    ("phone",      "verb"):          "Language & Study Tools",
    ("post",       "noun"):          "Language & Study Tools",
    ("post",       "verb"):          "Language & Study Tools",
    ("title",      "noun"):          "Language & Study Tools",
    ("sentence",   "noun"):          "Language & Study Tools",
    ("paragraph",  "noun"):          "Language & Study Tools",
    ("phrase",     "noun"):          "Language & Study Tools",
    ("page",       "noun"):          "Language & Study Tools",
    ("text",       "noun"):          "Language & Study Tools",
    ("text",       "verb"):          "Language & Study Tools",
    ("story",      "noun"):          "Language & Study Tools",
    ("type",       "noun"):          "Language & Study Tools",
    ("type",       "verb"):          "Language & Study Tools",
    ("dialogue",   "noun"):          "Language & Study Tools",

    # ── Food & Meals ────────────────────────────────────────────────────────
    ("bread",      "noun"):          "Food & Meals",
    ("rice",       "noun"):          "Food & Meals",
    ("chicken",    "noun"):          "Food & Meals",
    ("meat",       "noun"):          "Food & Meals",
    ("egg",        "noun"):          "Food & Meals",
    ("cheese",     "noun"):          "Food & Meals",
    ("butter",     "noun"):          "Food & Meals",
    ("cake",       "noun"):          "Food & Meals",
    ("sandwich",   "noun"):          "Food & Meals",
    ("salad",      "noun"):          "Food & Meals",
    ("soup",       "noun"):          "Food & Meals",
    ("dish",       "noun"):          "Food & Meals",
    ("lunch",      "noun"):          "Food & Meals",
    ("dinner",     "noun"):          "Food & Meals",
    ("breakfast",  "noun"):          "Food & Meals",
    ("cream",      "noun"):          "Food & Meals",
    ("salt",       "noun"):          "Food & Meals",
    ("sugar",      "noun"):          "Food & Meals",
    ("ice cream",  "noun"):          "Food & Meals",
    ("ice",        "noun"):          "Food & Meals",
    ("chocolate",  "noun"):          "Food & Meals",
    ("add",        "verb"):          "Food & Meals",
    ("cook",       "verb"):          "Food & Meals",
    ("cook",       "noun"):          "Food & Meals",
    ("cooking",    "noun"):          "Food & Meals",
    ("cut",        "verb"):          "Food & Meals",
    ("eat",        "verb"):          "Food & Meals",
    ("delicious",  "adjective"):     "Food & Meals",

    # ── Drinks & Dining Out ─────────────────────────────────────────────────
    ("water",      "noun"):          "Drinks & Dining Out",
    ("milk",       "noun"):          "Drinks & Dining Out",
    ("tea",        "noun"):          "Drinks & Dining Out",
    ("coffee",     "noun"):          "Drinks & Dining Out",
    ("juice",      "noun"):          "Drinks & Dining Out",
    ("beer",       "noun"):          "Drinks & Dining Out",
    ("wine",       "noun"):          "Drinks & Dining Out",
    ("menu",       "noun"):          "Drinks & Dining Out",
    ("restaurant", "noun"):          "Drinks & Dining Out",
    ("cafe",       "noun"):          "Drinks & Dining Out",
    ("drink",      "noun"):          "Drinks & Dining Out",
    ("drink",      "verb"):          "Drinks & Dining Out",
    ("order",      "verb"):          "Drinks & Dining Out",
    ("order",      "noun"):          "Drinks & Dining Out",

    # ── Travel & Movement ───────────────────────────────────────────────────
    ("go",         "verb"):          "Travel & Movement",
    ("travel",     "noun"):          "Travel & Movement",
    ("travel",     "verb"):          "Travel & Movement",
    ("trip",       "noun"):          "Travel & Movement",
    ("journey",    "noun"):          "Travel & Movement",
    ("visit",      "noun"):          "Travel & Movement",
    ("visit",      "verb"):          "Travel & Movement",
    ("stop",       "noun"):          "Travel & Movement",
    ("stop",       "verb"):          "Travel & Movement",
    ("walk",       "noun"):          "Travel & Movement",
    ("walk",       "verb"):          "Travel & Movement",
    ("run",        "noun"):          "Travel & Movement",
    ("run",        "verb"):          "Travel & Movement",
    ("holiday",    "noun"):          "Travel & Movement",
    ("vacation",   "noun"):          "Travel & Movement",
    ("passport",   "noun"):          "Travel & Movement",
    ("tourist",    "noun"):          "Travel & Movement",
    ("traffic",    "noun"):          "Travel & Movement",
    ("return",     "noun"):          "Travel & Movement",
    ("return",     "verb"):          "Travel & Movement",
    ("include",    "verb"):          "Travel & Movement",
    ("ever",       "adverb"):        "Travel & Movement",
    ("famous",     "adjective"):     "Travel & Movement",

    # ── Geography & Places ──────────────────────────────────────────────────
    ("city",       "noun"):          "Geography & Places",
    ("town",       "noun"):          "Geography & Places",
    ("country",    "noun"):          "Geography & Places",
    ("area",       "noun"):          "Geography & Places",
    ("island",     "noun"):          "Geography & Places",
    ("north",      "noun"):          "Geography & Places",
    ("north",      "adjective"):     "Geography & Places",
    ("north",      "adverb"):        "Geography & Places",
    ("south",      "noun"):          "Geography & Places",
    ("south",      "adjective"):     "Geography & Places",
    ("south",      "adverb"):        "Geography & Places",
    ("east",       "noun"):          "Geography & Places",
    ("east",       "adjective"):     "Geography & Places",
    ("east",       "adverb"):        "Geography & Places",
    ("west",       "noun"):          "Geography & Places",
    ("west",       "adjective"):     "Geography & Places",
    ("west",       "adverb"):        "Geography & Places",
    ("capital",    "noun"):          "Geography & Places",
    ("capital",    "adjective"):     "Geography & Places",
    ("world",      "noun"):          "Geography & Places",
    ("street",     "noun"):          "Geography & Places",
    ("place",      "noun"):          "Geography & Places",
    ("village",    "noun"):          "Geography & Places",
    ("park",       "noun"):          "Geography & Places",

    # ── Seasons & Natural World ──────────────────────────────────────────────
    ("spring",     "noun"):          "Seasons & Natural World",
    ("summer",     "noun"):          "Seasons & Natural World",
    ("autumn",     "noun"):          "Seasons & Natural World",
    ("winter",     "noun"):          "Seasons & Natural World",
    ("sea",        "noun"):          "Seasons & Natural World",
    ("fire",       "noun"):          "Seasons & Natural World",
    ("fall",       "noun"):          "Seasons & Natural World",
    ("climb",      "verb"):          "Seasons & Natural World",
    ("fly",        "verb"):          "Seasons & Natural World",
    ("high",       "adjective"):     "Seasons & Natural World",
    ("high",       "adverb"):        "Seasons & Natural World",
    ("light",      "adjective"):     "Seasons & Natural World",
    ("light",      "noun"):          "Seasons & Natural World",
    ("light",      "verb"):          "Seasons & Natural World",

    # ── School & Learning ───────────────────────────────────────────────────
    ("school",     "noun"):          "School & Learning",
    ("class",      "noun"):          "School & Learning",
    ("classroom",  "noun"):          "School & Learning",
    ("student",    "noun"):          "School & Learning",
    ("teacher",    "noun"):          "School & Learning",
    ("course",     "noun"):          "School & Learning",
    ("exam",       "noun"):          "School & Learning",
    ("lesson",     "noun"):          "School & Learning",
    ("homework",   "noun"):          "School & Learning",
    ("library",    "noun"):          "School & Learning",
    ("college",    "noun"):          "School & Learning",
    ("university", "noun"):          "School & Learning",
    ("learn",      "verb"):          "School & Learning",
    ("study",      "noun"):          "School & Learning",
    ("study",      "verb"):          "School & Learning",
    ("read",       "verb"):          "School & Learning",
    ("write",      "verb"):          "School & Learning",
    ("spell",      "verb"):          "School & Learning",
    ("practise",   "verb"):          "School & Learning",
    ("improve",    "verb"):          "School & Learning",

    # ── Academic Skills ─────────────────────────────────────────────────────
    ("problem",    "noun"):          "Academic Skills",
    ("mistake",    "noun"):          "Academic Skills",
    ("skill",      "noun"):          "Academic Skills",
    ("test",       "noun"):          "Academic Skills",
    ("test",       "verb"):          "Academic Skills",
    ("result",     "noun"):          "Academic Skills",
    ("example",    "noun"):          "Academic Skills",
    ("subject",    "noun"):          "Academic Skills",
    ("dictionary", "noun"):          "Academic Skills",
    ("science",    "noun"):          "Academic Skills",
    ("history",    "noun"):          "Academic Skills",
    ("geography",  "noun"):          "Academic Skills",
    ("reading",    "noun"):          "Academic Skills",
    ("report",     "noun"):          "Academic Skills",
    ("section",    "noun"):          "Academic Skills",
    ("practice",   "noun"):          "Academic Skills",

    # ── Family Members ──────────────────────────────────────────────────────
    ("mother",     "noun"):          "Family Members",
    ("father",     "noun"):          "Family Members",
    ("dad",        "noun"):          "Family Members",
    ("mum",        "noun"):          "Family Members",
    ("brother",    "noun"):          "Family Members",
    ("sister",     "noun"):          "Family Members",
    ("son",        "noun"):          "Family Members",
    ("daughter",   "noun"):          "Family Members",
    ("baby",       "noun"):          "Family Members",
    ("child",      "noun"):          "Family Members",
    ("parent",     "noun"):          "Family Members",
    ("grandparent","noun"):          "Family Members",
    ("grandmother","noun"):          "Family Members",
    ("grandfather","noun"):          "Family Members",
    ("husband",    "noun"):          "Family Members",
    ("wife",       "noun"):          "Family Members",
    ("aunt",       "noun"):          "Family Members",
    ("uncle",      "noun"):          "Family Members",
    ("cousin",     "noun"):          "Family Members",
    ("teenager",   "noun"):          "Family Members",
    ("adult",      "noun"):          "Family Members",

    # ── Social Life ─────────────────────────────────────────────────────────
    ("friend",     "noun"):          "Social Life",
    ("boyfriend",  "noun"):          "Social Life",
    ("girlfriend", "noun"):          "Social Life",
    ("member",     "noun"):          "Social Life",
    ("name",       "noun"):          "Social Life",
    ("name",       "verb"):          "Social Life",
    ("party",      "noun"):          "Social Life",
    ("family",     "noun"):          "Social Life",
    ("family",     "adjective"):     "Social Life",
    ("home",       "noun"):          "Social Life",
    ("home",       "adverb"):        "Social Life",
    ("home",       "adjective"):     "Social Life",
    ("together",   "adjective"):     "Social Life",
    ("club",       "noun"):          "Social Life",
    ("event",      "noun"):          "Social Life",
    ("company",    "noun"):          "Social Life",
    ("join",       "verb"):          "Social Life",
    ("come",       "verb"):          "Social Life",
    ("rule",       "noun"):          "Social Life",
    ("poor",       "adjective"):     "Social Life",

    # ── People & Society ────────────────────────────────────────────────────
    ("man",        "noun"):          "People & Society",
    ("woman",      "noun"):          "People & Society",
    ("boy",        "noun"):          "People & Society",
    ("girl",       "noun"):          "People & Society",
    ("people",     "noun"):          "People & Society",
    ("visitor",    "noun"):          "People & Society",
    ("card",       "noun"):          "People & Society",

    # ── Daily Routines ──────────────────────────────────────────────────────
    ("happen",     "verb"):          "Daily Routines",
    ("begin",      "verb"):          "Daily Routines",
    ("choose",     "verb"):          "Daily Routines",
    ("check",      "verb"):          "Daily Routines",
    ("need",       "verb"):          "Daily Routines",
    ("want",       "verb"):          "Daily Routines",
    ("know",       "verb"):          "Daily Routines",
    ("use",        "verb"):          "Daily Routines",
    ("keep",       "verb"):          "Daily Routines",
    ("like",       "verb"):          "Daily Routines",
    ("prefer",     "verb"):          "Daily Routines",
    ("enjoy",      "verb"):          "Daily Routines",
    ("live",       "verb"):          "Daily Routines",
    ("build",      "verb"):          "Daily Routines",
    ("design",     "verb"):          "Daily Routines",
    ("design",     "noun"):          "Daily Routines",
    ("form",       "noun"):          "Daily Routines",
    ("form",       "verb"):          "Daily Routines",
    ("space",      "noun"):          "Daily Routines",
    ("part",       "noun"):          "Daily Routines",
    ("thing",      "noun"):          "Daily Routines",
    ("life",       "noun"):          "Daily Routines",
    ("bed",        "noun"):          "Daily Routines",
    ("food",       "noun"):          "Everyday Concepts",
    ("game",       "noun"):          "Everyday Concepts",
    ("break",      "verb"):          "Everyday Concepts",
    ("break",      "noun"):          "Everyday Concepts",
    ("dance",      "verb"):          "Everyday Concepts",
    ("dance",      "noun"):          "Everyday Concepts",
    ("dress",      "verb"):          "Everyday Concepts",
    ("fill",       "verb"):          "Daily Routines",
    ("lie",        "verb"):          "Daily Routines",
    ("compare",    "verb"):          "Everyday Concepts",
    ("fact",       "noun"):          "Everyday Concepts",
    ("interest",   "noun"):          "Everyday Concepts",
    ("interested", "adjective"):     "Everyday Concepts",
    ("kind",       "noun"):          "Everyday Concepts",
    ("language",   "noun"):          "Everyday Concepts",
    ("little",     "adjective"):     "Everyday Concepts",
    ("lot",        "pronoun"):       "Quantifiers & Determiners",
    ("lot",        "adverb"):        "Quantifiers & Determiners",
    ("lot",        "determiner"):    "Quantifiers & Determiners",
    ("own",        "pronoun"):       "Personal Pronouns",
    ("own",        "adjective"):     "Descriptive Adjectives",
    ("present",    "adjective"):     "Descriptive Adjectives",
    ("present",    "noun"):          "Everyday Concepts",
    ("situation",  "noun"):          "Everyday Concepts",
    ("building",   "noun"):          "Everyday Concepts",
    ("let",        "verb"):          "Communication Basics",
    ("help",       "noun"):          "Communication Basics",
    ("help",       "verb"):          "Communication Basics",
    ("difference", "noun"):          "Communication Basics",
    ("lot",        "noun"):          "Quantifiers & Determiners",

    # ── Work & Career ───────────────────────────────────────────────────────
    ("farmer",     "noun"):          "Work & Career",
    ("driver",     "noun"):          "Work & Career",
    ("reader",     "noun"):          "Work & Career",
    ("writer",     "noun"):          "Work & Career",
    ("customer",   "noun"):          "Work & Career",
    ("project",    "noun"):          "Work & Career",
    ("change",     "noun"):          "Work & Career",
    ("change",     "verb"):          "Work & Career",
    ("decide",     "verb"):          "Work & Career",
    ("prepare",    "verb"):          "Work & Career",

    # ── Shopping & Money extras ─────────────────────────────────────────────
    ("bank",       "noun"):          "Shopping & Money",
    ("cost",       "noun"):          "Shopping & Money",
    ("cost",       "verb"):          "Shopping & Money",
    ("spend",      "verb"):          "Shopping & Money",
    ("price",      "noun"):          "Shopping & Money",
    ("market",     "noun"):          "Shopping & Money",
    ("green",      "noun"):          "Food & Meals",
    ("fruit",      "noun"):          "Fruits & Vegetables",
    ("meal",       "noun"):          "Food & Meals",

    # ── Health extras ──────────────────────────────────────────────────────
    ("hospital",   "noun"):          "Health",
    ("nurse",      "noun"):          "Health",
    ("advice",     "noun"):          "Health",

    # ── Social Life extras ─────────────────────────────────────────────────
    ("culture",    "noun"):          "Social Life",
    ("group",      "noun"):          "Social Life",
    ("neighbour",  "noun"):          "Social Life",
    ("person",     "noun"):          "People & Society",

    # ── Communication / Speaking extras ───────────────────────────────────
    ("question",   "noun"):          "Communication Basics",
    ("talk",       "verb"):          "Communication Basics",
    ("telephone",  "noun"):          "Communication Basics",
    ("telephone",  "verb"):          "Communication Basics",

    # ── Travel extras ─────────────────────────────────────────────────────
    ("beach",      "noun"):          "Travel & Movement",
    ("lose",       "verb"):          "Travel & Movement",
    ("plan",       "noun"):          "Travel & Movement",
    ("way",        "noun"):          "Travel & Movement",

    # ── Geography extras ──────────────────────────────────────────────────
    ("action",     "noun"):          "Daily Routines",
    ("fall",       "verb"):          "Seasons & Natural World",
    ("umbrella",   "noun"):          "Weather & Climate",

    # ── Grammar / determiners ──────────────────────────────────────────────
    ("a",          "indefinite article"): "Personal Pronouns",
    ("the",        "definite article"):   "Personal Pronouns",
    ("book",       "noun"):          "Language & Study Tools",
    ("detail",     "noun"):          "Language & Study Tools",
    ("follow",     "verb"):          "Action Verbs",
    ("spelling",   "noun"):          "Academic Skills",
    ("teach",      "verb"):          "School & Learning",

    # ── Politics / Law ────────────────────────────────────────────────────
    ("age",        "noun"):          "People & Society",
    ("policeman",  "noun"):          "People & Society",
    ("police",     "noun"):          "People & Society",

    # ── Science extras (Biology) ──────────────────────────────────────────
    ("animal",     "noun"):          "Nature & Wildlife",
    ("body",       "noun"):          "Body & Fitness",
    ("die",        "verb"):          "Health",
    ("grow",       "verb"):          "Nature & Wildlife",
    ("little",     "determiner"):    "Quantifiers & Determiners",

    # ── Time extras ───────────────────────────────────────────────────────
    ("quick",      "adjective"):     "Descriptive Adjectives",
    ("second",     "determiner"):    "Numbers 1-20",

    # ── Shopping & Money: merge small categories ─────────────────────────
    # (these were in Personal Finance 4, Economics & Trade 2 → Shopping & Money)
    # Already handled by keeping them in Shopping & Money category

    # ── Health: merge Medical & Treatment (2) ───────────────────────────────
    # Already in Health

    # ── existing OK categories: no changes needed ───────────────────────────
    # Action Verbs, Emotions, Arts & Music, Calendar & Dates, Home & Housing,
    # Places & Directions, Sports, Duration & Frequency, Description, Fashion,
    # Nature & Wildlife, Professions, Music & Performance, Weather & Climate,
    # Body & Fitness, Fruits & Vegetables, Shopping & Money, Feelings & States,
    # Furniture & Objects, Language Skills, Media & Journalism, Transportation,
    # Computing & Internet, Visual Arts, Finance, Technology, Objects & Tools
}

# ── Categories to DELETE (their words fully remapped above) ────────────────
DELETE_CATS = {
    "Grammar", "Daily Life", "Communication", "Science", "Environment",
    "Time", "Education", "Family", "People", "Travel",
    "Food & Drink",
    # small ones being merged
    "Personal Development", "Personal Finance", "Speaking & Interaction",
    "Politics & Law", "Society & Community", "Business & Management",
    "Cooking & Meals", "Economics & Trade", "Medical & Treatment",
    "Crime & Justice", "Personal & Social",
}


def main():
    lessons = load_flat()
    a1_old = flat_to_nested(lessons, 'a1')

    # Collect all a1 words
    all_words = []
    for cat, words in a1_old.items():
        for w in words:
            all_words.append((cat, w))

    new_a1 = defaultdict(list)
    unassigned = []

    for orig_cat, w in all_words:
        key = (w['word'], w['class'])
        if key in REMAP:
            new_cat = REMAP[key]
        elif orig_cat in DELETE_CATS:
            unassigned.append((orig_cat, w))
            continue
        else:
            new_cat = orig_cat  # keep original category
        new_a1[new_cat].append(w)

    # ── Report ─────────────────────────────────────────────────────────────
    if unassigned:
        print(f"⚠️  {len(unassigned)} words not remapped (kept in originals or need manual check):")
        for cat, w in unassigned:
            print(f"   [{cat}] {w['word']} ({w['class']})")

    updated = replace_level(lessons, 'a1', dict(new_a1))
    save_flat(updated)

    # ── Summary ────────────────────────────────────────────────────────────
    cats = sorted([(len(v), k) for k, v in new_a1.items()], reverse=True)
    too_big   = [(n, c) for n, c in cats if n > 30]
    too_small = [(n, c) for n, c in cats if n < 5]
    ok        = [(n, c) for n, c in cats if 5 <= n <= 30]

    print(f"\n✅ Done! A1 reclassification complete.")
    print(f"   Categories: {len(cats)}")
    print(f"   Words:      {sum(n for n,_ in cats)}")
    print(f"   Too big (>30):  {len(too_big)}")
    print(f"   Too small (<5): {len(too_small)}")
    print(f"   OK (5–30):      {len(ok)}")

    if too_big:
        print("\n🔴 Still too big:")
        for n, c in too_big:
            print(f"   [{n:3}] {c}")

    if too_small:
        print("\n🟡 Still too small:")
        for n, c in too_small:
            print(f"   [{n:3}] {c}")

    print("\n📋 All categories:")
    for n, c in cats:
        bar = "🔴" if n > 30 else ("🟡" if n < 5 else "🟢")
        print(f"   {bar} [{n:3}] {c}")


if __name__ == '__main__':
    main()
